name: Slack Notify with Buttons

on:
  workflow_dispatch:

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message with buttons
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "C0763JX6X6X",
              "text": "Deployment requires approval!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: *Deployment Ready* \nPlease approve or reject the deployment."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Approve"
                      },
                      "style": "primary",
                      "value": "approve",
                      "action_id": "approve_button"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Reject"
                      },
                      "style": "danger",
                      "value": "reject",
                      "action_id": "reject_button"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}