name: Build Pipeline

on:
  workflow_dispatch:
    
  push:
    branches:
      - master

permissions:
  contents: write

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Application with Maven (Capture Logs)
        id: build_app
        run: |
          set +e
          echo "Running mvn clean package..."
          mvn clean package --batch-mode --no-transfer-progress > build_output.log 2>&1
          BUILD_STATUS=$?
          echo "::group::Maven Output (tail)"
          tail -n 50 build_output.log || echo "No output file"
          echo "::endgroup::"
          if [ $BUILD_STATUS -ne 0 ]; then
            echo "Build failed, capturing logs..."
            tail -n 50 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
            ERROR_MSG=$(cat error.log)
            echo "error_message=$ERROR_MSG" >> "$GITHUB_OUTPUT"
          fi
          exit $BUILD_STATUS
        shell: bash

      - name: Show Error Message Output
        if: failure()
        run: |
          echo "Captured Error Output:"
          echo "${{ steps.build_app.outputs.error_message }}" 

      - name: Prepare Error Log for Deployment
        if: failure()
        run: |
          mkdir -p "${{ github.run_number }}"
          cp error.log "${{ github.run_number }}/error.log"

      - name: Deploy
        if: failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.run_number }}
      
      - name: Upload Error Log File
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            title: "🚨 Build Error Log"
            file: "./error.log"
            filename: "error.log"
            initial_comment: ":x: Build failed. Here's the full error log."

      - name: Wait for 5 seconds
        if: failure()
        run: sleep 5      

      - name: Slack Notification - Build Failed
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: ":x: *Build Failed* for *${{ github.repository }}* :boom:"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    *Repository:* `${{ github.repository }}`
                    *Branch:* `${{ github.ref_name }}`
                    *Triggered by:* `${{ github.actor }}`
              - type: "actions"
                elements:
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Explain"
                    style: "primary"
                    value: "https://devopsrehan.github.io/springboot-tictactoe/${{ github.run_number }}"
                    action_id: "explain_click"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Fix"
                    style: "primary"
                    value: "https://devopsrehan.github.io/springboot-tictactoe/${{ github.run_number }}"
                    action_id: "fix_click"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Re-run"
                    style: "danger"
                    value: "{\"run_id\": \"${{ github.run_id }}\"}"
                    action_id: "rerun_click"

      # - name: Slack Notification - Build Succeeded
      #   if: success()
      #   uses: slackapi/slack-github-action@v2.1.0
      #   with:
      #     method: chat.postMessage
      #     token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     payload: |
      #       channel: "${{ secrets.SLACK_CHANNEL_ID }}"
      #       text: "🚀 New deployment is ready! Would you like to proceed?"
      #       blocks:
      #         - type: "section"
      #           text:
      #             type: "mrkdwn"
      #             text: "🚀 New deployment is ready! Would you like to proceed?"
      #         - type: "actions"
      #           elements:
      #             - type: "button"
      #               text:
      #                 type: "plain_text"
      #                 text: "Approve"
      #               style: "primary"
      #               value: "approve"
      #               action_id: "approve_action"
      #             - type: "button"
      #               text:
      #                 type: "plain_text"
      #                 text: "Reject"
      #               style: "danger"
      #               value: "reject"
      #               action_id: "reject_action"