name: Build Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Application with Maven (Capture Logs)
        id: build_app
        run: |
          set +e
          echo "Starting Maven build..."

          mvn clean package --batch-mode --no-transfer-progress 2> build_error.log
          EXIT_CODE=$?

          echo "Build exited with status: $EXIT_CODE"
          
          # Always print error log for debugging
          echo "::group::Build Error Log"
          cat build_error.log || echo "No error log file found"
          echo "::endgroup::"

          # Export error log to GitHub output (if any)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "error_message<<EOF" >> $GITHUB_OUTPUT
            tail -n 50 build_error.log >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

          exit $EXIT_CODE
        shell: bash

      - name: Slack Notification - Build Failed
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":x: *Maven Build Failed* for *${{ github.repository }}* :bangbang:\n*Commit:* `${{ github.sha }}`\n*Message:* _${{ github.event.head_commit.message }}_\n*Author:* ${{ github.actor }}\n*Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n*Error Log:*```${{ steps.build_app.outputs.error_message || 'No error captured.' }}```",
              "channel": "#build-notifications"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Build Succeeded
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Maven Build Succeeded* for *${{ github.repository }}* :rocket:\n*Commit:* `${{ github.sha }}`\n*Message:* _${{ github.event.head_commit.message }}_\n*Author:* ${{ github.actor }}\n*Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
