name: Build Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven  

      - name: Build Application with Maven
        id: build_app
        run: |
          set -euo pipefail
          mvn clean package --batch-mode --no-transfer-progress 2> build_error.log || {
          echo "error_message<<EOF" >> $GITHUB_OUTPUT
          tail -n 50 build_error.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit 1
          }

      - name: Run Tests
        if: success()  
        run: |
          set -euo pipefail
          mvn test --batch-mode --no-transfer-progress
        shell: bash

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app-${{ github.run_number }}
          path: target/*.jar
          retention-days: 2

      - name: Slack Notification - Build Failed
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":x: Maven Build Failed for *${{ github.repository }}*\n> *Commit*: `${{ github.sha }}` - _${{ github.event.head_commit.message }}_\n> *Author*: ${{ github.actor }}\n> *Run*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n>*Error Snippet:*```${{ steps.build_app.outputs.error_message }}```",
              "channel": "#build-notifications"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Build Succeeded
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":white_check_mark: Maven Build Succeeded for *${{ github.repository }}*\n> *Commit*: `${{ github.sha }}` - _${{ github.event.head_commit.message }}_\n> *Author*: ${{ github.actor }}\n> *Run*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "channel": "#build-notifications"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}