name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      pom_path:
        description: 'Select the pom.xml file to use'
        required: true
        type: choice
        options:
          - './pass-pom.xml'
          - './fail-pom.xml'
  # push:
  #   branches:
  #     - master

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Application with Maven (Capture Logs)
        id: build_app
        run: |
          set +e
          echo "Running mvn clean package..."
          mvn clean package --file "${{ github.event.inputs.pom_path }}" --batch-mode --no-transfer-progress > build_output.log 2>&1
          BUILD_STATUS=$?

          echo "::group::Maven Output (tail)"
          tail -n 30 build_output.log || echo "No output file"
          echo "::endgroup::"

          if [ $BUILD_STATUS -ne 0 ]; then
            echo "Build failed, capturing logs..."
            tail -n 30 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
            ERROR_MSG=$(cat error.log)
            echo "error_message=$ERROR_MSG" >> "$GITHUB_OUTPUT"
          fi

          exit $BUILD_STATUS
        shell: bash

      - name: Show Error Message Output
        if: failure()
        run: |
          echo "Captured Error Output:"
          echo "${{ steps.build_app.outputs.error_message }}"

      - name: Slack Notification - Build Failed
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C0763JX6X6X"
            text: ":x: *Maven Build Failed* for *${{ github.repository }}* :boom:"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":x: *Maven Build Failed* for *${{ github.repository }}* :boom:\n*Commit:* `${{ github.sha }}`\n*Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n*Error Log:*```${{ steps.build_app.outputs.error_message || 'No error log captured.' }}```"
              - type: "actions"
                elements:
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Explain"
                    style: "primary"
                    value: "explain_error"
                    action_id: "explain_click"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Fix"
                    style: "primary"
                    value: "fix_error"
                    action_id: "fix_click"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Re-run"
                    style: "danger"
                    value: "rerun_pipeline"
                    action_id: "rerun_click"

      - name: Slack Notification - Build Succeeded
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C0763JX6X6X"
            text: "🚀 New deployment is ready! Would you like to proceed?"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "🚀 New deployment is ready! Would you like to proceed?"
              - type: "actions"
                elements:
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Approve"
                    style: "primary"
                    value: "approve"
                    action_id: "approve_action"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Reject"
                    style: "danger"
                    value: "reject"
                    action_id: "reject_action"

      # - name: Upload Error Log File
      #   if: failure()
      #   uses: slackapi/slack-github-action@v2.1.0
      #   with:
      #     method: files.uploadV2
      #     token: ${{ secrets.SLACK_BOT_TOKEN }}
      #     payload: |
      #       channel_id: "C0763JX6X6X"
      #       title: "🚨 Build Error Log"
      #       file: "error.log"
      #       filename: "error.log"
      #       initial_comment: ":x: Build failed. Here's the full error log."