name: Build and Deploy Application

on:
  workflow_dispatch:
    inputs:
      deploy_app:
        description: 'Do you want to deploy after build?'
        required: true
        default: false
        type: boolean

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Application with Maven
        run: |
          set -euo pipefail
          mvn clean package --batch-mode --no-transfer-progress
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.deploy_app == 'true' }}

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
          path: target/

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -euo pipefail

          echo "🚀 Triggering deployment on Render..."
          response=$(curl -s -w "%{http_code}" -o response.json -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}')

          if [[ "$response" -ne 201 ]]; then
            echo "❌ Deployment failed. HTTP Status: $response"
            echo "🔍 Render API Response:"
            cat response.json
            exit 1
          else
            echo "✅ Deployment triggered successfully!"
          fi
        shell: bash
