name: Re-run a workflow  
    
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Enter Run ID'
        required: true
        type: string
     

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Re-run workflow
        run: |
          curl -X POST https://api.github.com/repos/devopsRehan/fastapi-slack-handler/actions/runs/15581135012/rerun \
            -H "Authorization: Bearer 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" \
            -H "Accept: application/vnd.github+json"
